# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem "byebug"
gem "sinatra"
gem "activerecord"
gem "sqlite3"
gem "httparty"
gem "dotenv", groups: [:development, :test]
gem "one_take", path: "../" # for test in localhost
gem "rackup", "~> 2.2"
gem "puma", "~> 7.1"
